### PR TITLE
Ardupilog.m: Also add ylabel when ploting on an explicit axis

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by Georacer** [comment]
I had purposely not added the y-label when the user passes the axis handle explicitly, as that would overwrite the label from the previous plot command.
As a result, the latest plot would decide the y-label text.

In this case, I would prefer if the user explicitly set the y-label, in the case of multiple plots with different units involved.

Do you have a different use-case in mind that I didn't consider?

**Comment by Georacer** [comment]
FYI, I just added a fix in the plotting function, as the multiplier information wasn't used.

**Comment by amilcarlucas** [comment]
Thanks. The ylabel simplifies my code in a particular location. But you are right, I can fix it in another way.

**Comment by Georacer** [comment]
Okay, I'll close this then.

**Pull request closed without merging**
