### PR TITLE
do not crash on duplicate record

### PR DESCRIPTION
**Pull request by IRezkov**

### CODE REVIEW

**Comment by Georacer** [comment]
Hello!

Thanks a lot for the PR! Can you say in one or two sentences what does it fix so that I can add it in the changelog?

It would also be ideal if you could provide me with an example log, so that I can add it in my "makeshift CI", so that I can run tests against it for future regressions.

Best wishes for the new year!

**Comment by Georacer** [comment]
Also, you indentation is a bit off, but I think I can fix it myself with a commit on top of your PR. If I have troubles doing so I might ask you to fix it yourself.

**Comment by IRezkov** [comment]
I got a trouble with the ardupilot 4.2.3-based logs. I got duplicated records (can't say why) and it appeared error:
`Error using Ardupilog/addprop
'PRXR' is already defined as a property.

Error in Ardupilog/createLogMsgGroups (line 323)
						addprop(obj, newName);

Error in Ardupilog/readLog (line 133)
            obj.createLogMsgGroups(data');

Error in Ardupilog (line 67)
            readLog(obj);`

See sample log
[2023_problem.zip](https://github.com/Georacer/ardupilog/files/10328024/2023_problem.zip)

About intending, it looks ok with tab=4.

**Comment by Georacer** [comment]
Thank you! I'll merge it soon.

**Comment by isso11** [comment]
Thank you @Georacer ,

I modified the lines according to the PR. I used the PR and worked fine. But I just commented out line #322.

 `%  addprop(obj, newName);       % commented out`
```
                    try
                        addprop(obj, newName);
                    catch
                        warning('duplicated %d/%s', newType, newName);
                    end


                    obj.(newName) = new_msg_group;
                end
```

**Comment by isso11** [comment]
Thanks @fagoth for the PR.

**Review by isso11 — APPROVED** [review]

**Comment by Georacer** [comment]
I have specialized the try block a bit and made the warning message a bit more explicit.
Thank you for the contribution!

**Pull request merged**
