### PR TITLE
Ardupilog.m: fix filtering on Matlab 2021a

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by Georacer** [comment]
Hi! Thanks for the PR.

It looks like the filter function was broken for my R2017a, but it's also broken with your PR.
I'll see what I can do to fix it for me, but I'd like you to double check on 2021a. 

Is that ok?

**Comment by Georacer** [comment]
I'd like to patch this PR. According to the Github documentation, I would be able to do so if you give me write access to this particular branch.
It should be a tickbox on the right:
image

Can you please tick it?

**Comment by amilcarlucas** [comment]
It's ticked. I need to add you to my repo. just a sec.

**Comment by amilcarlucas** [comment]
Invitation sent.

**Comment by Georacer** [comment]
It worked after all!
Merged, thanks for finding this!

**Pull request merged**
