### PR TITLE
Waitbar+speedup

### PR DESCRIPTION
**Pull request by hunt0r**
Added a waitbar, made small modifications to speed up log reading, and other minor updates

### CODE REVIEW

**Comment by Georacer** [comment]
You merged master to waitbar+speedup. That shouldn't be done; instead we should merge waitbar+speedup to master.
Did you misclick somewhere?

**Comment by Georacer** [comment]
This is what the repo looked some moments ago:
before
Notice how `master` merges into `waitbar`. This shouldn't happen.

I rewinded the last commit of `waitbar` to undo the merge with `git reset --hard HEAD^1` and force-pushed the branch to the repo.
This is how it looks now.
after


BEFORE doing any more work in this branch, re-fetch it locally to update your local branch for the history change

**Comment by Georacer** [comment]
In general, you should never merge `master` into another `branch`. Only other branches get merged into master.
You'll get the hang of it.

**Comment by Georacer** [comment]
I changed the waitbar to fill as a percentage of the selected num of lines, not the total. What do you think?

**Comment by hunt0r** [comment]
Oops! I need some practice, sorry. I tried to merge my local master-branch into the github's waitbar+speedup.  Sorry for the confusion, and thanks for straightening it out!

**Comment by hunt0r** [comment]
I think the "waitbar as percentage" needs some work, because num_lines is a bit hack-ish to begin with.

The main for-loop can terminate 2 ways: 1) processing just the number of lines input by the user (num_lines) or 2) by finishing the log completely. So the hack is that if the user instructs Ardupilog to read the whole log, I just set num_lines = 10*obj.numMsgs to ensure the end of log occurs before the counter actually reaches that number. But in this case, num_lines is not a good estimate in the waitbar for the end of the log.

**Comment by Georacer** [comment]
Okay. Can you then create an auxiliary variable `waitbar_max=obj.numMsgs`, before you increase `obj.numMsgs` tenfold.
Then, use that as a denominator for the waitbar.

Re github:
1. Checkout `waitbar+speedup`
2. `git pull origin waitbar+speedup`
3. make changes and commit
4. `git push origin waitbar+speedup`

**Comment by hunt0r** [comment]
I think I don't understand the purpose of the waitbar change? It was waitbar(ctr/obj.numMsgs, ...) which would make the red gui-bar show the percentage of the completion. What's the purpose of creating a local variable waitbar_max? It appears to me to have the same behavior?

**Comment by Georacer** [comment]
I just wanted it to fill up to 100% in the case where the user requested a smaller amount of lines to be parsed.

**Comment by Georacer** [comment]
Okay, I think I managed to correct, per your suggestions.

**Pull request merged**
