### PR TITLE
delete-empty-msgs

### PR DESCRIPTION
**Pull request by Georacer**
I made A LOT of changes this time, so please check that I didn't break anything.
Two major additions:
1. A delete empty msgs function which I cannot make it act on the calling object. It can only return another object
2. A filter function, which allows a message filter to be applied on an existing Ardupilog

Comments and/or patches welcome.

I think I did a bit of a mess this time. I may try to tidy the code up a bit next time.

### CODE REVIEW

**Comment by Georacer** [comment]
Addresses #32

**Review by hunt0r — APPROVED** [review]
I think these are good changes, in the right direction. As you noted, we might consider some cleanup or bug-fixes afterwards, but I'm in favor of approving and then modifying with future PR's.

**Comment by hunt0r** [comment]
One bug I find: when using message filtering, I don't think Ardupilog.numMsgs counts only the included messages. I haven't dug into why.

EDIT: I just noticed 738923-738101 = 822, the desired number. Maybe it's accidentally counting excluded (filtered) messages, rather than included ones?

(e.g. when using master branch, l = Ardupilog('39.BIN', {'FMT', 'PARM'}; then l.numMsgs = 822 while l.totalLogMsgs = 738923.  When using this branch instead, l.numMsgs = 738101)

**Comment by hunt0r** [comment]
Is the new filterMsgs() function called anywhere? Or is the design that the user would manually filter?

**Comment by Georacer** [comment]
I'll take a look re: the number of msgs and get back to you.

**Comment by Georacer** [comment]
filterMsgs() isn't called by anyone. It's meant as a user API function, in the case where you read a whole log and don't want to re-parse it to get a subset of it.

**Comment by Georacer** [comment]
Turns out I had a bug in my logic. Fixed now. Please check.

Two more things:
1. Notice that both filterMsgs() and deleteEmptyMsgs() do not operate on the log, but create a new one.
I thought this was a good practice. What do you think?
2. Upon reading a new log, I intentionally leave empty msg groups intact. This is to signify their existence, as prescribed by the FMT message. A slight modification would be to delete the empty msg groups only when the msg filter is not empty (which means the user doesn't want to see other msgs). What do you think?

**Comment by hunt0r** [comment]
I agree the bug is fixed, thanks.

1) Yes, this seems like the best idea. The user could always overwrite their old log with the new one if they desired that behavior.
2) I agree with your idea, it makes sense that an unfiltered log, which has FMT-defined message groups but no actual data for them, should have them as empty LogMsgGroups. I'm not sure I understand the 2nd part... if someone filters a log (either initially, or using the new filterMsgs() functionality) then the empty LogMsgGroups will be filtered (or preserved) according to the filters, right? So their emptiness doesn't matter?

**Comment by Georacer** [comment]
Yeah, I think you're right. I'm kind of burnt out right now. But let me throw another scenario:
If the msgFilter includes `MSG` but the `MSG` group is empty. The filtered output log will not include `MSG` because it will be deleted as empty.

Is a patch needed here to keep it in the filtered log, albeit empty?

**Comment by hunt0r** [comment]
I'm in favor of merging this patch, then re-considering fixes/upgrades in the future as our use-cases become more apparent.

**Comment by Georacer** [comment]
Cool! Go ahead.

**Pull request merged**
