### PR TITLE
Added initial files from mavlink-inspector to kicstart repo

### PR DESCRIPTION
**Pull request by Georacer**
Just importing a couple of basic files able to parse a cleartext .bin file and create the basic structure.
Also added a .gitignore file

### CODE REVIEW

**Comment by hunt0r** [comment]
Is this pull still relevant? The formatDoc.txt and .gitignore files are good, but are the other 2 outdated?

**Comment by Georacer** [comment]
That was the initial PR I had done, just to kickstart the project.
The other 2 files were my previous work on the same topic, but you have already replaced it.
Perhaps we could bring them in, in case we want to also support cleartext logs.
Can we keep them around, in a "Deprecated" folder?

**Comment by hunt0r** [comment]
Yes, that sounds good. This is a good chance for me to learn Github techniques... should I accept the pull request then issue one with a move to the "Deprecated" folder? Or can/should I modify the pull request before accepting?

**Comment by Georacer** [comment]
I will edit the PR by pushing the change in the same branch. Once I do 
I'll let you know and you can merge it.

**Comment by Georacer** [comment]
So, I 
* pulled the remote master onto my local repo
* rebased local/initial_files onto local/master, to ensure no conflicts occured
* created the "deprecated" folder and moved the 2 files inside it
* *force* pushed the local/initial_files onto the remote (`git push -f origin initial_files`). The "force" option was necessary because I wanted to re-write history and git doesn't let us do that implicitly. This is for our protection, because now your local/initial_files (if you have one) is incompatible with the remote. Essentially, I have changed history as you see it for your local repo. However, we can get away with it when we work with experimental, per-feature branches. On the other hand, re-writing the history of the _master_ branch would be a big no-no.

**Comment by Georacer** [comment]
This is ready for merging, when you are.

**Pull request merged**
